### ISSUE TITLE
Data Frame name: Basin Analysis

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#37]
This is not a new bug, but a design flaw/limitation of the original BAGIS. The default Layers data frame is renamed to Basin Analysis whenever an AOI is loaded in BAGIS. The original BAGIS mapping functions apply cartography settings on the Basin Analysis data frame. If the named data frame cannot be located by BAGIS, then the maps cannot be correctly created.

![image](https://cloud.githubusercontent.com/assets/11510708/26082608/a74c47cc-3985-11e7-8ed2-05a728d37cd9.png)

To trigger the error message, you just open a New map document (the Basin Analysis data frame will be reset to a name called Layers) and try to use the map functions from the menu or from the auto pseudo site dialog window.  Can you check if Data Frame is named "Basin Analysis" whenever a new map is being created and rename the Data Frame if it's not called Basin Analysis?

You should be able to find the routine that changes a Data Frame name under the Set AOI tool of the AOI Utilities dialog window.

**Comment by lbross** [comment]
I can fix this but there is a slight conflict between the methods that set the Data Frame name and that check to see what the name is. BA_SetDefaultMapFrameName sets the name of the FocusMap to "Basin Analysis". BA_ZoomToAOI (the method that generates the error message) checks to see if the name of the first layer is "Basin Analysis". These are not necessarily always the same thing if there are multiple data frames.

So ... do we want to use the FocusMap or the first map?

**Comment by jdduh** [comment]
The correct mapping procedure should have an initial step that perform the following check:

If "Basin Analysis" Data Frame exists, then make it the default/focused map frame, else rename the default/focused map frame to "Basin Analysis"

**Comment by lbross** [comment]
This is fixed in the next release of BAGIS. Moved BA_SetDefaultMapFrameName into class library so it could be used by BA_ZoomToAOI.

**Comment by jdduh** [comment]
It seems the data frame name issue is resolved. Two more issues:
1. The layout view is not zoomed/panned to layout extent. I have to use the Zoom to Whole Page tool to see the layout every time I selected the "Scenario 1 Representation" map from the menu.

![image](https://cloud.githubusercontent.com/assets/11510708/26171326/65d92556-3af9-11e7-867a-671af305b341.png)

2. I got an error message when using the Site Representations tool to view a specific site (by double-clicking on the site). To reproduce this error, you just need to open a new map document (without exiting out ArcMap). It seems the site representation map is dependent on the Scenario representation map.

![image](https://cloud.githubusercontent.com/assets/11510708/26171280/3f4e1856-3af9-11e7-93d4-2d9eef915653.png)

**Comment by lbross** [comment]
Allowing the data frame to be renamed later in BAGIS is generating multiple issues. It seems that multiple properties are set when the AOI is selected. Opening up a new map document disposes of these settings and I'm having a difficult time re-setting them for the maps. The original code is confusing too because it manipulates the data frame properties in multiple places. The layout view not being zoomed to layout extent is symptomatic of this. I am also having trouble getting the AOI extent to set correctly publishing a map to a new map document.

I was going to suggest that we leave the old error message in place and tell the user that they need to reset the AOI if the Basin Analysis frame is missing but that doesn't seem to resolve the layout or extent issues. I will look at this again later. Only restarting ArcMap helps.

**Comment by lbross** [comment]
I am close to a resolution for item 1. My fix for the original issue had some unintended consequences.

With regard to the site scenario maps and the site representation tool. Yes. All of those maps depend on having the original site scenario representation map loaded. They turn some of the layers on and off but the base layers are shared. Would it be acceptable to implement a check for all of those buttons to see if the original site scenario representation map is still loaded? If not, I would pop a message telling the user to click the maps button on the site scenario form and disable the site scenario buttons on the menu.

**Comment by jdduh** [comment]
It would be nice if you can check if the required layers for site representation maps exist and add them to ArcMap if they don't. A related issue is that I notice there are excessive redraws of the layers when using the "Map" functions of the auto site or the site scenario tools. Excessive redraw is especially obvious when working on a slower computer.

**Comment by lbross** [comment]
I've been working on this today and am almost done. I checked the behavior on the current maps buttons before starting. As with the site scenario buttons, the maps rely on the maps being initially loaded from the maps form, and then you toggle the layers with a map button. If you click one of the map buttons after a new map document is loaded, nothing happens which is not desirable.

After spending 2+ days in this code, it's kind of a mess and I'd rather not replicate it by loading the component maps in > one place. The site scenario code is worse than the maps code because I built on top of it. 

I added some error handling today that disables the map buttons if the underlying map is no longer loaded and directs the user to reload using the Maps form. I've done something similar with the site scenario buttons. Given that these are an edge cases and only apply if the user loads a new map document, I hope this is acceptable.

I plan to have a new build for you this afternoon because the current one has a LOT of issues loading the maps. My fix for the original issue really went sideways. Will take a look at the excessive redraws next week. Do you see it with the maps as well? Or just site scenario?

**Comment by jdduh** [comment]
All these mapping menu items seem to work fine, without excessive redraws. 

![image](https://cloud.githubusercontent.com/assets/11510708/26263400/86a3eba0-3c8d-11e7-874e-7e0a3ada9da2.png)

**Comment by lbross** [comment]
Good. I will compare those mapping items to the site scenario mapping items.

**Comment by lbross** [comment]
Fixed the buttons that manipulated the site scenario maps. They were re-adding the vector layers to change the color when we can just change the color on the existing layers. Most of the utility methods to add the layers included the directive to refresh the activeView. I took this out and all the maps still seemed to load correctly, and a little faster. We'll have to keep an eye out to see if there are any unintended consequences.

**Comment by jdduh** [comment]
Most of the issues have been resolved. However, sometimes the initial extent of the map layout is not set correctly. This occurs when you alternate the display of the site representation maps and the basin analysis maps.

![image](https://user-images.githubusercontent.com/11510708/26999703-069515fa-4d55-11e7-8739-d8f8316f9322.png)

**Comment by lbross** [comment]
Added call to all basin analysis buttons to zoom to aoi extent. This will be in the next release of BAGIS V3.

**Comment by jdduh** [comment]
The bug has been fixed. However, the Map function on the site scenario dialog windows takes excessive layer redraw/reload when switching between, for example, the Scenario 1/2 representation maps or the Auto-Site Map tool.

**Comment by jdduh** [comment]
It seems that if you click on the Site Scenario's Map button twice in a row. Most of the layers are removed and re-added to the map. Is the removal necessary? Or a fresh will update the maps when the source data were updated?

Try the following steps to see excessive layer updates:
1. Use the Site Scenario's Map button to create maps.
2. Use the Auto Pseudo-Site's Map button to create maps.
3. Use  the Site Scenario's Map button to re-create the maps. You will see a lot of screen refreshes here.

**Comment by lbross** [comment]
The Site Scenario Map button is similar to the Maps button on the Map Settings page, that is, it sets up the map for first viewing with all the layers in the correct order. It works a little differently in that I remove all the layers first, but all of the 'Add layer' subroutines remove the layer before trying to add. With the Map Settings page the removal happens incrementally as each layer is added rather than all at once in the beginning.

In the example you gave, step 3 should be to use the Scenario 1, Scenario 2, or Difference in Scenarios buttons to view the Site Scenario map again. This will toggle the appropriate layers like the other maps buttons.

I know this is inconsistent with the Pseudo-Site map. Should we add a button to the maps menu to toggle the Pseudo-site layers on?

**Comment by jdduh** [comment]
Ok, I see that the Generate Maps map button behaves the same. Let's not worry about the "excessive" refresh now. Other mapping issues seem to have been fixed.
