### ISSUE TITLE
Auto-site log tool - precipitation information is displayed wrong

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#46]
Here are the lines from the log file:

![image](https://user-images.githubusercontent.com/11510708/27898085-09009916-61d9-11e7-8f5e-03541b93fb5e.png)

And this is what's on the log dialog window:
The upper precipitation value I used is 40.

![image](https://user-images.githubusercontent.com/11510708/27898118-35b9970a-61d9-11e7-9644-09551385b7e0.png)

**Comment by lbross** [comment]
This was a problem with both storing and displaying the data. It will still display incorrectly for sites generated prior to the next release of BAGIS V3. This was also a problem with displaying the form for the most recent site created. However, it will all be fixed in the next release of BAGIS v3.
