### ISSUE TITLE
Auto pseudo site tool - cache previous search settings and results

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#50]
Users might use the same search criteria for subsequent pseudo sites. Also, consider using the constraint layers created in the previous runs if the constraints remain unchanged (given that only represented area layer will be different in the subsequent runs).

**Comment by jdduh** [comment]
Some notes from the communication with Gus.

 Is it possible to retain the previous location, elevation, proximity, precipitation information in the auto-pseudo site selection view even after user has re-calculated represented area?  When using the iterative approach described above, I have to keep redefining selection criteria.  Alternatively, user could specify the number of pseudo sites to recommend and the application could automatically cycle through, retaining the search area criteria for each iteration.

First, the sequential method we currently use to find multiple 'optimal' sites definitely will find different locations than the simultaneous method, which is the conceptually correct method for finding multiple 'optimal' sites. (Imaging the task of cutting a string into equal segments, the sequential method will not generate string segments of equal length in most cases.) Second, we need a way to keep track of which (pseudo) sites were actually used in Scenario 1 (and scenario 2 too) given that we allow users to deselect some of the sites listed in the scenario. This also affects the implementation of your #4 suggestion (4.      Include pseudo sites in the “tables” output if I go back and rerun the tables, including area-elevation curve location, and elev-precip scatter plot.). It's doable, but the current GUI needs to be expanded greatly to handle this capability.

**Comment by lbross** [comment]
Do you think this would work?
1. Add a checkbox to the existing p-site form: "Add the new site to scenario 1 and recalculate the represented area for scenario 1". We would want to remove all the layers from the display because some of them would be removed by the recalculation. It would leave the display in an odd state. The user could use the 'Maps' button to re-display the maps.
2. Add a copy button to the existing p-site form: This would allow the user to copy the parameters used to create the site from either the most recent, or any site in the log. They would have to choose a new name for the site. Then they could calculate like usual.

In Gus' use case one would:
1. Calculate the first site with the new recalculate option selected
2. When the calculation is finished, the most recent configuration would still be on the form
3. Use the copy button to create a new site and give it a unique name
4. Calculate the next site

This could be done iteratively until no more sites can be created.

We could choose not to delete the constraint layers if the recalculate button were selected. I would want to add some sort of id to the name that we can keep track of (or store them in their own gdb) so that we use the correct layers. Not sure how we can automatically clean these up when the user is done adding multiple sites...

**Comment by lbross** [comment]
Prototype slides published to https://drive.google.com/open?id=1EHl0ND30ts22BTWvEVwnVdfaI_H3BP7fnBLOro2ky04

**Comment by jdduh** [comment]
Color-coded comments are posted on the google slides.

**Comment by lbross** [comment]
The function that calculates the Represented Area does 3 calculations: scenario 1 represented area, scenario 2 represented area, and difference in representation. When calculating the represented area from the p-site screen after adding a p-site, it seems to me that we should only recalculate scenario 1 and the difference in representation. Technically the user COULD have changed their selection in the scenario 2 grid since the previous calculation, but I think the likelihood of this is low. We will save processing time by skipping the recalculation of scenario 2. @jdduh: What do you think?

**Comment by lbross** [comment]
See https://docs.google.com/presentation/d/1EHl0ND30ts22BTWvEVwnVdfaI_H3BP7fnBLOro2ky04/edit?usp=sharing for design details. This will be initially implemented in v3.2-b1.

**Comment by jdduh** [comment]
It would be nice if the program tracks if Scenario 2 is changed to determine if a recalculation is required.

**Comment by lbross** [comment]
I can work on this in July. Do you think this logic would work?
1. Create a variable in the site scenario form to track if the scenario 2 sites change. Because site scenario is a dockable window, this would be a session-level variable.
2. The only way to save the list of scenario 2 sites between sessions is to use the Calculate button. There is no save button. Thus, we can assume when the form is opened for the first time that the represented area(s) match the sites listed on the form. Set the recalculate variable to false.
3. There are 4 arrow buttons on the site scenario form to add/remove sites to scenario 2. If these are used at all, set the recalculate variable to true.
4. If calculate is called, use the recalculate variable to determine if scenario 2 should be recalculated. Set the variable to false when finished. Calculate can be called from either the Site Scenario form or the auto-site form.

**Comment by lbross** [comment]
Implemented per my previous comments
