### ISSUE TITLE
Create AOI from a shapefile - make PRISM clipping buffer adjustable

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#51]
This is an urgent request by NWCC. Please include this enhancement in BAGIS V3.1 release ASAP.

The regular AOI creation workflow has a backdoor for users to specify a PRISM buffer distance (see the image below). Is there a similar backdoor for the Create AOI from a shapefile tool? The reason for hiding the PRISM buffer setting is that some users might not know the significance of using a large enough buffer distance to clip the 1 km by 1 km PRISM data.

![image](https://user-images.githubusercontent.com/11510708/28982281-2032bc34-790a-11e7-9e7d-aa7f271fe3f1.png)

Can you add a similar backdoor for the Create AOI from a shapefile tool? Users need to double-click on the Buffer Distance text to open the PRISM buffer distance dialog window.

![image](https://user-images.githubusercontent.com/11510708/28982439-b9481324-790a-11e7-9a00-f1e75f331a7c.png)

**Comment by lbross** [comment]
This is fixed and will be in the next release of BAGIS v3.1.

**Comment by jdduh** [comment]
Here is a related enhancement request that we might as well just get it done.

The AOI Utilities dialog window has a function to re-clip PRISM, SNOTEL, and Snow Course layers. I believe a buffer is used in these clipping. Please make it possible for users to change the buffer distance. Here is a proposed GUI modification. Users can double-click on the label text to change the buffer distance. Please also include it in BAGIS 3.1.

![gui](https://user-images.githubusercontent.com/11510708/29100163-d51870f6-7c5e-11e7-8267-65fba41fdd27.png)

**Comment by lbross** [comment]
Please review and approve the attached UI. I moved a couple of things around from your mock-up so that it would fit better on the form. The enabling of the buffer distance labels is dependent on if the layer is selected for clipping. I also updated the error handling and processing in the original Create AOI and Create AOI from shapefile so that all 3 work the same way. The AOI forms didn't have any edits to ensure the buffer distance was numeric and would crash if it was not.

![clip](https://user-images.githubusercontent.com/11527966/29145507-566987a4-7d12-11e7-9198-c6f21833b58b.png)

**Comment by lbross** [comment]
Thinking through the implementation. The clipping is based on a vector layer. For the PRISM layers this is straightforward. We will recreate p_aoi_v and p_aoi with the new buffer distance. We will have a flag that tracks whether or not the user double-clicked on the PRISM label text so we will avoid most unnecessary processing.

The site layers clip buffer distance is not so simple. We have many more layers that use the boundaries from aoib and aoib_v so if we recreate those, the extent of other layers that were clipped to the original buffered boundary will be different. I recommend creating a new vector file for clipping. Is this something we want to keep in the aoi? Name? Or should it be deleted when clipping is done? Should it be added to the list of files that is stored in eBAGIS? We will also use a flag here so we can use the original buffered boundary if the user didn't change it.

**Comment by jdduh** [comment]
Is there a way to figure out what the AOI (DEM) buffer distance was? If yes, then we can just report that distance and not allowing the distance be changed. Please implement the PRISM buffer distance as what you suggest.

**Comment by jdduh** [comment]
Please do some basic verification on the texts entered for the buffer distance. If it's not numeric, then prompt an error message and ignore the change.

**Comment by lbross** [comment]
We don't log any of the parameters used to generate an AOI. We could calculate the buffer distance by calculating the absolute difference between aoib_v and aoi_v of IEnvelope.LowerLeft. If we do this, we should check first to confirm that the linear unit for both is meters. It should be because BAGIS should have created them, but just in case. Note that this will increase the time that it takes to set the AOI on the AOI Utilities form. I believe this was an issue in the past.

**Comment by lbross** [comment]
Please also let me know what we should display for the initial PRISM buffer. Right now I just display 1000 since that is the default.

**Comment by jdduh** [comment]
Please just implement the PRISM buffer setting feature and use 1000 meters as the default. Ignore the SNOTEL and Snow Course enhancement request (there is no need to show the buffer distance).
