### ISSUE TITLE
ArcGIS 10.5 compatible issues

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#60]
Please RDP to GGR-CH-424H-G0 to test BAGIS and ArcGIS 10.5 (and later) compatibility. There is an issue with RDP setup on the machine. I will update this document when the issue is resolved.

**Comment by lbross** [comment]
So I shouldn't try to RDP until I hear back from you that the issue is fixed? Can you install VS Express 2010 here as well so that I can debug and compile? Also ArcObjects SDK? If I can't debug, the best I can do is MessageBox errors and I probably won't be able to fix anything unless I can compile against the new version.

**Comment by lbross** [comment]
Actually according to [ESRI's website](https://desktop.arcgis.com/en/system-requirements/10.5/arcobjects-sdk-system-requirements.htm), we will need either Microsoft Visual Studio 2013 VB .NET or Microsoft Visual Studio 2015 VB .NET Community edition to install the SDK and compile the add-in for 10.5.

**Comment by jdduh** [comment]
The RDP issue has been resolved. You should be able to connect to the computer with your ODIN account. I have also installed MS VS 2015 VB .NET Community edition and ArcGIS 10.5.1 SDK on the computer.

**Comment by jdduh** [comment]
After selecting a pourpoint and proceeding to clipping AOI layers, this error occurred. This error is specific to ArcGIS 10.5 (or later versions).

![image](https://user-images.githubusercontent.com/11510708/40866573-436affcc-65b3-11e8-9a60-645b2a0a2b25.png)

**Comment by lbross** [comment]
I'm having trouble connecting to this computer. I have VPN'd into PSU. I am using GGR-CH-424H-G0 for the computer name and PSU\lbross for the user name. Do you have any suggestions for me to try? Do I need to fully qualify the computer name? I have tried both geog.pdx.edu and psu.ds.pdx.edu.

**Comment by jdduh** [comment]
I just tested the connection and it worked. The computer name is
ggr-ch-424H-G0.psu.ds.pdx.edu. You should log on with PSU\lbross.

Jiunn-Der (Geoffrey) Duh

Geography, Portland State University

Cramer Hall 424, 1721 SW Broadway

Portland, OR 97201, USA

tel: +1-503-725-3159
fax: +1-503-725-3166

web.pdx.edu/~jduh

**Comment by lbross** [comment]
I was able to connect with the computer and run Visual Studio

**Comment by lbross** [comment]
Unfortunately we need to load 2 more pieces of software to this computer for the development environment: Git For Windows 2.0 and TortoiseGit. I tried to install TortoiseGit this morning and it requires admin privileges. I downloaded both software installers to the Downloads folder on the lab computer. There are some configuration suggestions on [this page](https://tortoisegit.org/support/faq/#prerequisites) for the Git For Windows install. If it's possible to give me admin privileges, I could do the installations myself.

My plan is to create a separate branch for 10.5 so we can merge changes down from the master branch and maintain it separately for a while as needed. I hope this is all we have to install but it's been a while since I installed TortoiseGit.

One of the first things I will look at once I get it working is issue #62. I have a feeling this is a version incompatibility issue and migrating to 10.5 may provide some insight.

**Comment by lbross** [comment]
Made some progress on this. Needed to remove and re-add references to GISClient and Server. Got strange errors related to IGPProcess that I couldn't resolve or find information about. Switched to .NET Framework 4.5 and these went away. There were a couple of obsolete syntax lines that needed to be fixed. Now I am stuck with this error:
The "ValidateAddInXMLTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0

Per ESRI support we need to install an additional component for Visual Studio 2015. I do not have installation privileges.
https://support.esri.com/en/technical-article/000012659

**Comment by jdduh** [comment]
Both Github for Windows and TortoiseGit were installed. Please give them a try.

**Comment by jdduh** [comment]
Visual Studio 2013 Shell was also installed.

**Comment by lbross** [comment]
Making good progress. Got add-in to compile and debugger to run. Here are some changes I needed to make:
1. Remove and re-add ESRI.ArcGIS.ADF.Connection.Local library. This was confusing because the library didn't show up on the list to add. I needed to browse to it. But once I found it, I could add it.
2. Change these 2 tags in the Config.esriaddinx file: `<Target name="Desktop" version="10.5" /> <AddIn language="CLR" library="BAGIS.dll" namespace="BAGIS">`

Getting the debugger to work:
1. Create test ArcMap project in 10.5 to generate *.vbproj.user file. Rename and copy into BAGIS project
2. Set ArcMap as 'Start External Program' in debug section of project properties

**Comment by lbross** [comment]
Apparently the pHydrologyOp.SnapPourPoint() method has changed between 10.2.2. The pourpoint is now indicated with a value of '1' instead of '0'.  This means that the 10.5 code will need to remain a separate branch from 10.2.2. I will do a search to see if we use SnapPourPoint() elsewhere in BAGIS

Note that the IGxDialog also seems to take a much longer time to load than in previous versions. Actually most interactions with ArcCatalog are slower.

**Comment by lbross** [comment]
Need to set 'Copy Local' settings for ESRI libraries to false to make add-in package smaller. Visual Studio appears to randomly change this setting when importing the older project.

**Comment by lbross** [comment]
We have deployed an add-in for AGS 10.5. Code for the add-in will be maintained on GitHub branch ags_10.5. My methodology is to fix any bugs in the master branch (10.2.2) and to merge these fixes into the ags_10.5 branch so the branches stay as close as possible prior to 10.5's promotion to the supported version.
