### ISSUE TITLE
Error when Basin path name contains a space

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#68]
User got this error message when creating an AOI. The error occurred during the DEM smoothing step. The user was able to complete the AOI creation after removing the space in the path. This probably is an ArcInfo GRID data issue.

![image](https://user-images.githubusercontent.com/11510708/49404480-6cace480-f704-11e8-9166-f1fedb58c065.png)

**Comment by lbross** [comment]
This is dialog when clipping the DEM to create a basin rather than creating an AOI. Do you know if this was uncovered on AGS 10.2.2 or 10.5? I couldn't recreate it on 10.2.2.

The Smooth tool uses the Geoanalyst API. Given the nature of this error message, we may want to consider switching over to Geoprocessor.

**Comment by jdduh** [comment]
It's on 10.5. I believe 10.5 has messed up the raster file handling routines, similar to what we experienced with the Extract by Mask tool. Should we direct temporary output rasters to a default FGDB, instead of a folder? If the output raster doesn't have any extension name (e.g., .img or .tif) and is saved to a folder, then the raster is stored in ArcInfo GRID format, which imposes limitation on some tools when the file path string contains spaces.

Please switch to Geoprocessor.

**Comment by lbross** [comment]
I just created a basin on 10.5 with a space in the name and it didn't generate an error. I think this is a problem with the a GeoAnalyst tool (INeighborhoodOp) not managing its' temporary files correctly. As you indicated, this has gotten worse in 10.5. Restarting ArcMap to remove the spaces from the folder name fixed the problem rather than actually changing the folder name.

We have an existing GP method for Focal Statistics. I will switch to that and keep the rest of the code the same as much as possible.

The ExtractByMask issue was an outlier that I haven't seen with any of the other GP tools.

**Comment by lbross** [comment]
I will also be making this change in the 'Create AOI from Shapefile' tool because it uses the same Smooth function

**Comment by lbross** [comment]
This is complete for both 10.2.2 and 10.5 and will be included in the next release

**Comment by jdduh** [comment]
Got this error when enabling Smoothing in BASIN creation.
![image](https://user-images.githubusercontent.com/11510708/54319633-79fd2900-45a7-11e9-94f5-402c438b3544.png)

Here is a catalog view of the BASIN folders.
![image](https://user-images.githubusercontent.com/11510708/54319694-a9ac3100-45a7-11e9-9ec8-100014482b74.png)

**Comment by jdduh** [comment]
The tool works fine when the smooth option is disabled.

**Comment by lbross** [comment]
This is a strange bug. For some reason ArcMap is setting the snap raster path to the basin filled_dem before running the FocalStatistics GP tool. I don't know where this is coming from, as I am not doing it. In all of the GP methods, I only set the snap raster if one is passed into the method. And it is specific to the BASIN so it isn't pulling it from my local ArcMap settings. If a snap raster path isn't passed into the method, I have always assumed that the snap raster will be empty in the GP which it always has been. I added logic to all of the GP methods to set the snap raster to nothing if a snap raster is NOT passed in. I am testing but this appears to have fixed the problem.

Also I noticed that the using the button to add the reference layers was silently throwing an exception because it was using the BA_Read_Settings() method which is intended to be used when loading frmSettings. I switched it to use BA_ReadBAGISSettings which loads the BA_SystemSettings variables but not the form.
