### ISSUE TITLE
Generate Maps Tool - BA_SaveRasterDatasetGDB HRESULT error 

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#72]
Got this error when running the Generate Zone analysis on Kara's AOI.

![image](https://user-images.githubusercontent.com/11510708/54320230-79659200-45a9-11e9-88d3-5dde0b3287a4.png)

**Comment by jdduh** [comment]
I run the tool in ArcGIS 10.6.1. The AOI has one snow courses site and doesn't have any snotel site (one snotel site outside the AOI boundary).

**Comment by lbross** [comment]
I'm not able to recreate this error on 10.5.1. I suspected that this might be happening because there is a snotel_sites feature class with no features in this AOI. This isn't a valid BAGIS configuration. If there aren't any snotel sites in the AOI, the layer shouldn't exist. But on 10.5.1, the generate maps tool seems to handle the lack of features correctly.

Also in the error screen shot, the status message shows that it is working on the Snow Course elevation zones which means that the snotel zones should have completed successfully.

Maybe try it again in a fresh session of 10.6.1? If that fails, can you try on 10.5.1? Or let me know if you want me to start developing on 10.6.1 instead of 10.5.1. Remember they are not backwards compatible.

Update: Just looked at the code and this may be coming from the BA_ReclassRasterFromIntervalList() method which uses the GeoAnalyst RasterReclassOp class. As we've found, these GeoAnalyst classes become less stable with each version of ArcMap so it's possible that it is broken in 10.6.1 :-(

**Comment by jdduh** [comment]
Tested it on 10.5.1 and everything is fine. Just beware that the current release is not 10.6.1 compatible.

**Comment by lbross** [comment]
Do you want me to switch the reclass to the Geoprocessor and see if that fixes it on 10.6.1? It should work the same as before on 10.5.1.

**Comment by jdduh** [comment]
Yes, please switch. Thanks!

**Comment by lbross** [comment]
I ran into trouble with using the GP tool for reclassing because it has a higher degree of precision than the Geoanalyst tool. When we generate the reclass string we use the AOI_DEMMin and AOI_DEMMax to set the upper and lower bound for the classes. You may remember that we set these values based on the unbuffered AOI but the filled_dem is often buffered. When I used the reclass string on the filled_dem, there were a few pixels outside of the reclasses on the upper and lower end which messed up the snotel and snow course zones because these pixels weren't assigned to the correct class.

After figuring out what was happening, I added a mask (the unbuffered AOI) to the geoprocessor reclass tool. This appears to solve the problem and give a similar result to the Geoanalyst tool.

I am applying the same logic to all of the zones datasets and switching them all over to the geoprocessor. My question is, with the PRISM zones, is it OK to use the unbuffered AOI as the mask? Or do I need to use the PRISM buffer AOI? This dataset didn't seem to have a problem without any mask.

Hopefully this makes sense.

**Comment by jdduh** [comment]
Can you create a document on github or our bagis google site describing how bagis uses different AOI buffers in analysis? I believe that generate maps tool also has its own rules (and probably prefers using the buffered AOI). We should use the buffered PRISM in analysis to prevent "missing" data caused by the huge cell size difference between DEM and PRISM, unless bagis resamples PRISM to DEM resolution before the analysis. See the screenshot below.

![image](https://user-images.githubusercontent.com/11510708/54575273-af8f8100-49b0-11e9-8467-5412d135c979.png)

**Comment by lbross** [comment]
I chose a more surgical approach for the analysis mask for the zone layers. I'm using the prism buffer mask for prism layers and the unbuffered mask for the snotel and snow course zones. All the other layers use the buffered mask because they don't set the interval on elevation. Let me know when you would like me to post a new add-in to test on 10.6.1.

Update: I saw your comment from last night after posting mine. Do you want me to update the code that sets the AOI_DEMMin and AOI_DEMMax based on the unbuffered AOI boundary? This is shared by both the maps tool and the AOI Info tool. This code pre-dates me but it seems to have been done deliberately in the BA_GetDemStatsGDB() method. 
Here are the comments in that section:
               >use the unbufferred aoi to mask out the dem
               >Use the AOI extent for analysis
               >Open AOI Polygon to set the analysis mask
I'll have to think about the best way to document buffer usage. The task seems overwhelming when I think about having to read through all the code for the tools.

**Comment by jdduh** [comment]
Yes, please build one with the most recent updates. I will test it on 10.5.1 and 10.6.1.
Please don't go through the code to figure out the AOI buffer usage, just document what you know. I will search my email messages to see if NWCC made any specific requests on the basin analysis extent (i.e., buffered versus unbuffered). I believe we might have some github discussions related to this issue.
